version: '3.3'

services:
  backend:
    image: app:latest
    ports:
      - 8080:8080
    privileged: true
  postgres:
    image: postgres:16.3
    container_name: data-postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt