version: '3.3'

services:
  backend:
    image: app:latest
    ports:
      - 8080:8080
    privileged: true
#    environment:
#      - POSTGRES_DB=example
#  postgres:
#    image: postgres:latest
#    restart: always
#    secrets:
#      - db-password
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_DB=example
#      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#    expose:
#      - 5432
#volumes:
#  db-data:
#secrets:
#  db-password:
#    file: db/password.txt